version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: maijjd-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: maijjd123
      MONGO_INITDB_DATABASE: maijjd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/mongodb:/docker-entrypoint-initdb.d
    networks:
      - maijjd-network

  # Backend API
  backend:
    build:
      context: ./backend_maijjd
      dockerfile: Dockerfile
    container_name: maijjd-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5001
      MONGODB_URI: mongodb://admin:maijjd123@mongodb:27017/maijjd-backend?authSource=admin
      JWT_SECRET: maijjd_production_jwt_secret_key_2024
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - maijjd-network
    volumes:
      - ./backend_maijjd:/app
      - /app/node_modules

  # Admin Dashboard
  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: maijjd-admin-dashboard
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5002
      MONGODB_URI: mongodb://admin:maijjd123@mongodb:27017/maijjd-admin?authSource=admin
      JWT_SECRET: maijjd_production_jwt_secret_key_2024
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    networks:
      - maijjd-network
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules

  # Frontend (Development mode for internal use)
  frontend:
    build:
      context: ./frontend_maijjd
      dockerfile: Dockerfile
    container_name: maijjd-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_ADMIN_URL: http://localhost:5002
      REACT_APP_ANALYTICS_URL: http://localhost:5001/api
      REACT_APP_TRACKING_URL: http://localhost:5001/api/tracking
      REACT_APP_FEEDBACK_URL: http://localhost:5001/api/feedback
      REACT_APP_SOCKET_URL: http://localhost:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - admin-dashboard
    networks:
      - maijjd-network
    volumes:
      - ./frontend_maijjd:/app
      - /app/node_modules

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: maijjd-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - admin-dashboard
    networks:
      - maijjd-network

volumes:
  mongodb_data:

networks:
  maijjd-network:
    driver: bridge
